# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlackAuburn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlackAuburn

pod 'DZNEmptyDataSet'
pod 'ChameleonFramework'
pod 'Alamofire', '~> 4.6'
pod 'TextFieldEffects'
pod 'PKRevealController'
pod 'SlackTextViewController'
pod 'RETableViewManager', '~> 1.6'	
pod 'SVProgressHUD'
pod 'FontAwesomeKit/FoundationIcons'
pod 'SnapKit', '~> 4.0.0'
pod 'MGSwipeTableCell'
pod 'SwiftyJSON'
pod 'FSCalendar'
pod 'PopupDialog', '~> 0.7'


  
post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings[‘SWIFT_VERSION’] = ‘4.0’
            end
        end
    end

end
